import { Github, Linkedin, Mail, Phone, Shield, Globe, Terminal, Box, Lock, Cloud } from "lucide-react"

export const SITE_CONFIG = {
  title: "Maddipati Sarwansai — Cybersecurity Portfolio",
  description: "Final-year cybersecurity student & developer passionate about building secure, resilient digital solutions.",
  copyright: `© ${new Date().getFullYear()} Maddipati Sarwansai. All rights reserved.`,
}

export const PERSONAL_INFO = {
  name: "Maddipati Sarwansai",
  role: "Cybersecurity Student & Developer",
  tagline: "Securing the Digital Future, One System at a Time.",
  bio: "Final-year B.Tech Cybersecurity student specializing in network security, ethical hacking, and full-stack development. I build things that matter — with security at the core.",
  initials: "MS",
  location: "Telangana, India",
  cvLink: "https://drive.google.com/file/d/1EMgY5_nwdWGzjsufn6ma5Z-YIo-m3hZW/view?usp=drive_link",
  email: "sarwansai483@gmail.com",
  phone: "+91 9030118006",
  github: "https://github.com/sarwansai8",
  linkedin: "https://linkedin.com/in/maddipati-sarwansai",
}

export const NAV_LINKS = [
  { href: "#about", label: "About" },
  { href: "#education", label: "Education" },
  { href: "#achievements", label: "Achievements" },
  { href: "#skills", label: "Skills" },
  { href: "#projects", label: "Projects" },
  { href: "#contact", label: "Contact" },
]

export const CONTACT_INFO = [
  {
    icon: Mail,
    label: "Email",
    value: PERSONAL_INFO.email,
    href: `mailto:${PERSONAL_INFO.email}`,
    description: "Best for project discussions",
  },
  {
    icon: Phone,
    label: "Phone",
    value: PERSONAL_INFO.phone,
    href: `tel:${PERSONAL_INFO.phone.replace(/\s+/g, "")}`,
    description: "Available 9am–7pm IST",
  },
  {
    icon: Github,
    label: "GitHub",
    value: "github.com/sarwansai8",
    href: PERSONAL_INFO.github,
    description: "Check out my projects",
  },
  {
    icon: Linkedin,
    label: "LinkedIn",
    value: "linkedin.com/in/maddipati-sarwansai",
    href: PERSONAL_INFO.linkedin,
    description: "Professional networking",
  },
]

export interface Project {
  id: string
  title: string
  subtitle: string
  duration: string
  category: string
  status: string
  image: string
  description: string
  impact: string
  technologies: string[]
  github: string
  problem: string[]
  outcome: string[]
  keyContributions: string[]
  role: string
  // Optional legacy/extended fields used by the project detail page
  liveDemo?: string
  longDescription?: string
  features?: string[]
  metrics?: Record<string, string>
}

export const projectsData: Project[] = [
  {
    id: "1",
    title: "CyberTrapX — Advanced Honeypot System",
    subtitle: "Multi-Layered Threat Detection Framework",
    duration: "2024 – Present",
    category: "Cybersecurity",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Lead Developer — Sole architect responsible for system design, deployment automation, and threat logging infrastructure.",
    description:
      "A sophisticated, multi-layered honeypot framework engineered to detect, log, and analyze unauthorized access attempts and malicious activity across networked environments. Automated cross-platform deployment reduces setup from hours to minutes.",
    impact: "Automated honeypot deployment from hours to minutes on Linux & Windows",
    technologies: ["Python", "Flask", "PowerShell", "Bash"],
    github: "https://github.com/sarwansai8/Advanced-Multi-Layered-Honeypot-System",
    problem: [
      "Organizations struggle to detect early-stage intrusions — traditional firewalls provide no visibility into unknown or novel attack methods.",
      "Security teams lack actionable intelligence about attacker behavior, tools, and techniques (TTPs) because real production systems cannot be deliberately exposed.",
      "Deploying decoy systems (honeypots) manually is complex, time-consuming, and non-standardized.",
      "No unified, lightweight, open-source honeypot framework combines multi-service simulation, real-time logging, and cross-platform deployment in a single tool.",
    ],
    outcome: [
      "Delivered a fully functional multi-layered honeypot system capable of simulating real networked services and capturing attack behavior in real time.",
      "Automated cross-platform deployment via Python and PowerShell scripts — reducing honeypot setup time from hours to minutes.",
      "Generated structured log outputs (keylog.txt, logs.txt, email alerts) providing forensic-grade evidence trails for threat intelligence analysis.",
      "Established a reusable, environment-isolated framework with .env configuration management for secure deployment across environments.",
      "Created a tool directly applicable to enterprise SOC teams, penetration testers, and threat intelligence analysts.",
    ],
    keyContributions: [
      "Multi-service honeypot architecture simulating vulnerable services to attract and log attacker behavior.",
      "Cross-platform deployment automation using deploy.py and deploy.ps1 for Linux and Windows.",
      "Real-time logging pipeline capturing keystrokes, access events, and email-based alerts.",
      "Secure credential management with .env and .env.example configuration patterns.",
      "Forensic-ready log outputs supporting audit trails and post-incident analysis.",
    ],
  },
  {
    id: "2",
    title: "Wi-Fi Security Assessment Tool",
    subtitle: "Multi-Platform Network Auditing Framework",
    duration: "2024",
    category: "Network Security",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Full-Stack Security Developer — Designed the modular architecture and implemented all platform variants.",
    description:
      "A comprehensive, multi-platform Wi-Fi security assessment framework for authorized network auditing spanning Windows, Android (APK), and a web interface. Implements network discovery, WPA/WPA2 handshake capture, and password analysis.",
    impact: "Three independently deployable platform variants — Windows, Android, Web",
    technologies: ["Python", "Flask", "Buildozer", "Android SDK"],
    github: "https://github.com/sarwansai8/wifi-security-tool",
    problem: [
      "Network administrators and security professionals have no unified, accessible tool to assess Wi-Fi vulnerabilities across different device types and environments.",
      "Existing Wi-Fi security tools are predominantly desktop-only — leaving mobile field assessments without adequate tooling.",
      "Organizations cannot easily identify weak WPA/WPA2 implementations, rogue access points, or password policy gaps without expensive proprietary software.",
      "Non-technical stakeholders cannot visualize or understand Wi-Fi network exposure — creating a communication gap between security teams and management.",
    ],
    outcome: [
      "Built three independently deployable platform variants (Windows, Android APK, Web) — enabling security assessments from any device.",
      "Enabled field security assessments via the Android app, significantly expanding the operational reach of network auditing.",
      "Implemented network discovery, WPA/WPA2 handshake capture, and password analysis capabilities within a single, modular codebase.",
      "Reduced dependency on expensive proprietary tools by providing an open, educational framework with clear legal usage guidelines.",
      "Demonstrated practical multi-platform development capability — Python codebase compiled to Android APK via Buildozer.",
    ],
    keyContributions: [
      "Three independent deployment targets: Windows, Android (Buildozer APK), and Web (Flask).",
      "Network discovery, handshake capture, and password analysis in one modular framework.",
      "Isolated components (android_app.py, web_app.py, host_server.py) for flexible deployment.",
      "Legal and ethical use documentation built into the project from inception.",
      "Professional README with installation and setup instructions for all platforms.",
    ],
  },
  {
    id: "3",
    title: "Team Healthcare Portal",
    subtitle: "Production-Deployed Patient Management System",
    duration: "2024",
    category: "Full Stack",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Co-Lead Developer — Full-stack architecture, component design, deployment configuration, and security documentation.",
    description:
      "A production-deployed healthcare management portal (live on Vercel) providing patients and administrators with a unified interface for appointment scheduling, medical records, vaccination tracking, and admin oversight — with 96.4% TypeScript coverage.",
    impact: "Live on Vercel with 3 production environments — real deployment, not a demo",
    technologies: ["Next.js", "TypeScript", "MongoDB", "Vercel", "Jest"],
    github: "https://github.com/sarwansai8/Team",
    problem: [
      "Healthcare facilities managing appointments, medical records, and vaccination data across disconnected systems face operational inefficiencies and poor patient experience.",
      "Manual or paper-based workflows in smaller healthcare settings create risks of lost records, missed appointments, and non-compliance with health data management standards.",
      "Building a unified patient portal serving both patients and administrators simultaneously requires careful full-stack architecture.",
      "Healthcare portals must meet high standards for security, usability, and reliability, yet most existing solutions are either prohibitively expensive or technically inaccessible.",
    ],
    outcome: [
      "Delivered a fully functional, production-deployed healthcare portal live on Vercel with 3 active production environments.",
      "Unified appointment scheduling, medical records management, and vaccination tracking into a single TypeScript-safe, component-based application.",
      "Achieved 96.4% TypeScript coverage ensuring type-safe code across all application layers — reducing runtime errors and improving maintainability.",
      "Established comprehensive documentation (SECURITY_FEATURES.md, UI_UX_ENHANCEMENTS.md, FEATURE_SHOWCASE.md) reflecting enterprise-grade software engineering standards.",
      "Integrated Jest testing framework and custom React hooks, providing a scalable, test-ready codebase.",
    ],
    keyContributions: [
      "Production-deployed on Vercel with multiple live environments — real deployment, not local only.",
      "96.4% TypeScript codebase ensuring type-safe, maintainable application architecture.",
      "Multi-feature workflows: appointments, medical records, vaccination tracking, admin dashboard.",
      "Jest testing framework with jest.config.js and jest.setup.js integrated from project inception.",
      "PowerShell automation scripts for developer workflow and deployment preparation.",
    ],
  },
  {
    id: "4",
    title: "IoT Security — Smart Device Attack Detection",
    subtitle: "Research-Driven IoT Threat Detection Framework",
    duration: "2024",
    category: "IoT Security",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Security Researcher & Developer — Responsible for research scope, methodology design, and technical implementation.",
    description:
      "A research-driven cybersecurity project focused on identifying, classifying, and mitigating attack vectors targeting IoT smart devices. Designed a detection framework architecture targeting DDoS amplification, firmware exploitation, and credential brute-forcing.",
    impact: "Addresses one of the fastest-growing & most critically underserved enterprise security domains",
    technologies: ["Python", "Network Protocol Analysis", "IoT Frameworks"],
    github: "https://github.com/sarwansai8/IoT-Security-Detecting-Attacks-on-Smart-Devices",
    problem: [
      "IoT devices (smart cameras, sensors, industrial controllers, medical devices) are among the most vulnerable entry points in enterprise networks — yet they receive the least security attention.",
      "Unlike traditional IT systems, IoT devices often run minimal operating systems with no built-in security monitoring, making attack detection extremely difficult.",
      "There is no standardized, lightweight framework for detecting device-level attacks on heterogeneous IoT ecosystems — leaving organizations blind to intrusions.",
      "The volume of IoT deployments is growing exponentially (estimated 30+ billion connected devices globally), dramatically expanding the attack surface.",
    ],
    outcome: [
      "Established a dedicated research project specifically targeting IoT attack surfaces — filling a critical gap in the broader cybersecurity tooling landscape.",
      "Scoped a detection framework architecture designed to identify abnormal traffic patterns and behavioral anomalies characteristic of active IoT device attacks.",
      "Positioned the project as a foundation for implementing detection algorithms targeting DDoS amplification, firmware exploitation, and credential brute-forcing.",
      "Contributed to the open security research community by making the project publicly available, inviting collaboration and peer review.",
      "Developed domain expertise in one of the fastest-growing and highest-demand areas of enterprise cybersecurity.",
    ],
    keyContributions: [
      "Addresses IoT security — one of the most critically underserved domains in enterprise cybersecurity.",
      "Research framework targeting device enumeration, firmware vulnerabilities, and network intrusion.",
      "Designed for detection of DDoS amplification, credential attacks, and firmware exploitation patterns.",
      "Public repository enabling community collaboration and peer review.",
      "Foundation for planned implementation of detection algorithms and anonymized test datasets.",
    ],
  },
  {
    id: "5",
    title: "Library Management System",
    subtitle: "End-to-End Book & Member Management Platform",
    duration: "2023",
    category: "Full Stack",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Full-Stack Developer — Designed the system architecture, database schema, and all application logic.",
    description:
      "A complete library management system covering book cataloging, member registration, borrowing/return management, and overdue tracking. Built with a relational database schema supporting complex cross-table queries for real-time availability and history lookups.",
    impact: "Eliminated manual record-keeping errors through automated transaction logging",
    technologies: ["Python", "SQLite", "MySQL", "CRUD Architecture"],
    github: "https://github.com/sarwansai8/library-management-system-project-",
    problem: [
      "Libraries managing large book inventories manually face constant challenges with lost records, overdue tracking failures, and member management inconsistencies.",
      "Without a centralized system, librarians cannot efficiently track which books are available, borrowed, overdue, or reserved — leading to operational bottlenecks.",
      "Manual borrowing records are prone to human error, making auditing and reporting time-consuming and unreliable.",
      "Smaller institutions cannot afford expensive commercial library management software, creating a gap for an accessible, open-source alternative.",
    ],
    outcome: [
      "Delivered a fully functional library management system covering all primary workflows: book cataloging, member registration, borrowing, returns, and overdue tracking.",
      "Implemented a relational database schema supporting complex queries across books, members, and transaction records — enabling real-time availability and history lookups.",
      "Eliminated manual record-keeping errors through automated transaction logging and structured data storage.",
      "Built with modular Python architecture, making the system extensible to REST API or web interface integration with minimal refactoring.",
      "Demonstrated the ability to translate real-world operational requirements into production-ready software.",
    ],
    keyContributions: [
      "Full CRUD system covering catalogue, members, transactions, and overdue management.",
      "Relational database schema with complex cross-table query support.",
      "Modular Python backend extensible to REST API or web interface.",
      "Automated transaction logging eliminating manual record-keeping errors.",
      "Real-world domain requirement analysis translated into functional software.",
    ],
  },
  {
    id: "6",
    title: "Faculty & Student Management System",
    subtitle: "Iteratively Refined Academic Administration Platform",
    duration: "2023",
    category: "Full Stack",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Backend Developer — Designed database architecture and management logic across all three iterations.",
    description:
      "A series of three iteratively developed academic management systems (ms, ms1, ms2) for faculty administration, student records, and course management — each version addressing specific architectural limitations identified in the prior iteration.",
    impact: "3 versioned iterations demonstrating disciplined software development lifecycle maturity",
    technologies: ["Python", "SQL", "Relational DB Design"],
    github: "https://github.com/sarwansai8/faculty-and-student-ms",
    problem: [
      "Academic institutions managing faculty profiles, student enrollments, and course assignments across disconnected spreadsheets face significant administrative overhead.",
      "Many-to-many relationships between students, faculty, and courses are complex to manage manually — leading to scheduling conflicts, missing enrollment records, and reporting inaccuracies.",
      "First-generation management systems often have architectural limitations that only become apparent under real usage — requiring deliberate iterative refinement.",
      "Without a centralized system, generating reports on student performance, faculty workload, or course enrollment requires time-consuming manual data aggregation.",
    ],
    outcome: [
      "Delivered three progressively refined management system versions — each addressing specific architectural limitations identified in the prior iteration.",
      "Implemented comprehensive data management covering student enrollment, faculty profiles, course assignments, and academic record maintenance in a single integrated system.",
      "Resolved complex many-to-many data relationships through deliberate relational schema design, enabling accurate cross-entity queries and reporting.",
      "Demonstrated a disciplined software development lifecycle: plan, build, evaluate, refine — a methodology directly valued in enterprise Agile environments.",
      "Built a scalable backend capable of supporting administrative reporting, enrollment analytics, and faculty workload visibility.",
    ],
    keyContributions: [
      "Three versioned iterations demonstrating systematic, improvement-driven development discipline.",
      "Complex many-to-many relationship modeling between students, faculty, and courses.",
      "Comprehensive academic workflows: enrollment, faculty management, course assignments, records.",
      "Each version documents specific improvements over the prior implementation.",
      "Python backend with relational database design focused on data integrity and query efficiency.",
    ],
  },
  {
    id: "7",
    title: "Portfolio Website (Next.js)",
    subtitle: "Professional Personal Portfolio with Dark Mode",
    duration: "2024 – Present",
    category: "Frontend",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Frontend Developer — Designed and implemented the complete UI architecture, dark mode system, and project showcase components.",
    description:
      "A fully custom, production-ready portfolio website using Next.js and TypeScript — the same stack used by leading technology companies. Implements a complete dark mode system using React context and CSS variables with 96.9% TypeScript coverage.",
    impact: "96.9% TypeScript coverage — production-grade, enterprise-standard frontend architecture",
    technologies: ["Next.js", "TypeScript", "React", "PostCSS", "Node.js"],
    github: "https://github.com/sarwansai8/portfolio",
    problem: [
      "Developers without a professional portfolio are invisible to recruiters — even strong GitHub profiles require a polished, branded presentation layer.",
      "Static resume documents cannot showcase interactive projects, live demos, or technical design decisions — limiting the depth of first impressions.",
      "Building a portfolio on template platforms (Wix, WordPress) signals limited technical capability — a developer's personal site should demonstrate their engineering skill.",
      "Most developer portfolios lack dark mode support, responsive design, and modern React patterns — resulting in poor user experience.",
    ],
    outcome: [
      "Built a fully custom, production-ready portfolio website using Next.js and TypeScript — the same stack used by leading technology companies.",
      "Implemented a complete dark mode system using React context and CSS variables — demonstrating advanced UX engineering and accessibility awareness.",
      "Created a dynamic, component-based architecture allowing effortless addition of new projects, skills, and sections without structural refactoring.",
      "Achieved 96.9% TypeScript coverage ensuring maintainable, error-resistant frontend code.",
      "Established a professional online presence directly embedded in the portfolio itself — turning the website into a live technical demonstration.",
    ],
    keyContributions: [
      "96.9% TypeScript codebase on Next.js App Router — production-grade frontend architecture.",
      "Full dark mode system using React context and CSS variables.",
      "Dynamic routing and component-based design for scalable content management.",
      "Organized structure: app, components, hooks, lib, styles, public directories.",
      "Configured with PostCSS, TypeScript config, and modern tooling from day one.",
    ],
  },
  {
    id: "8",
    title: "Cyber Course — Educational Platform",
    subtitle: "Structured Cybersecurity Learning Platform",
    duration: "2023",
    category: "Education",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Course Developer & Content Architect — Designed the curriculum structure and developed all course content.",
    description:
      "An HTML-based educational platform delivering structured cybersecurity learning content from foundational to intermediate concepts. Self-contained with no third-party dependencies — accessible offline and easily deployable on any web server.",
    impact: "Public contribution to open security education — accessible offline with zero dependencies",
    technologies: ["HTML", "CSS", "Web Content Architecture"],
    github: "https://github.com/sarwansai8/Cyber-Course",
    problem: [
      "Cybersecurity education is fragmented across dozens of platforms, YouTube channels, and documentation sites — making it extremely difficult for beginners to follow a structured learning path.",
      "Most free cybersecurity learning resources are either too theoretical (academic papers) or too advanced (CTF platforms) — leaving a gap for structured intermediate content.",
      "Learners without access to expensive certifications (CEH, OSCP, CompTIA Security+) have no formal pathway to build foundational security knowledge.",
      "Organizations onboarding junior security team members lack affordable, customizable training materials tailored to their specific security stack.",
    ],
    outcome: [
      "Delivered a structured, web-accessible cybersecurity course covering foundational to intermediate security concepts in a clear, progressive learning sequence.",
      "Created a self-contained educational platform requiring no third-party dependencies — accessible offline and easily deployable on any web server.",
      "Demonstrated the rare ability to translate deep technical security expertise into accessible, structured educational content.",
      "Established a publicly available security education resource, contributing directly to community knowledge-sharing.",
      "Positioned as a well-rounded security professional capable of both building security tools and communicating security concepts clearly.",
    ],
    keyContributions: [
      "Structured cybersecurity curriculum from foundational to intermediate concepts.",
      "Self-contained HTML platform with no external dependencies — offline accessible.",
      "Demonstrates ability to translate technical expertise into accessible educational content.",
      "Public contribution to open security education and community knowledge sharing.",
      "Supports security awareness, onboarding, and training use cases.",
    ],
  },
  {
    id: "9",
    title: "Next.js Boilerplate",
    subtitle: "Professional-Grade Starter Template",
    duration: "2024",
    category: "Developer Tools",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Template Architect — Designed the project scaffolding, TypeScript configuration, and development workflow.",
    description:
      "A professional-grade Next.js starter template with TypeScript pre-configured, designed to accelerate modern web application development. Eliminates 2–4 hours of repetitive setup with a scalable folder structure applicable from prototype to enterprise scale.",
    impact: "Eliminates 2–4 hours of repetitive setup per new project",
    technologies: ["Next.js", "TypeScript", "Node.js", "PostCSS", "ESLint"],
    github: "https://github.com/sarwansai8/nextjs-boilerplate",
    problem: [
      "Every new Next.js project requires repetitive, time-consuming setup: TypeScript configuration, folder structure, ESLint, PostCSS — often taking hours before feature work begins.",
      "Development teams without standardized project templates make inconsistent architectural decisions — creating maintenance overhead and onboarding friction.",
      "Junior developers and freelancers frequently start new projects with suboptimal structures that become technical debt within weeks.",
      "Rapid prototyping and hackathon scenarios demand immediate productive development — zero-config templates are essential for speed without sacrificing code quality.",
    ],
    outcome: [
      "Delivered a production-ready Next.js boilerplate eliminating 2–4 hours of repetitive setup for every new project.",
      "Enforced consistent TypeScript-first architecture across all projects using the template — reducing type errors and improving code review efficiency.",
      "Established a scalable folder structure (app, components, lib, hooks, styles, public) applicable to projects from prototype to enterprise scale.",
      "Enabled immediate productive development from project day one — critical for freelance projects, client engagements, and competitive hackathons.",
      "Demonstrated senior-level engineering thinking: the ability to abstract patterns, reduce friction, and enforce architectural consistency at scale.",
    ],
    keyContributions: [
      "Eliminates 2–4 hours of repetitive setup for every new Next.js project.",
      "TypeScript-first configuration with optimized tsconfig.json for App Router.",
      "Scalable folder conventions applicable from prototype to enterprise scale.",
      "Immediately productive — zero-config start with full TypeScript support.",
      "Reusable for client projects, hackathons, and rapid prototyping engagements.",
    ],
  },
  {
    id: "10",
    title: "Java Academic Projects",
    subtitle: "OOP, Data Structures & Algorithms Assessments",
    duration: "2022 – 2023",
    category: "Academic",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Developer — Implemented all projects as part of formal computer science curriculum.",
    description:
      "A collection of Java programming projects (java.exam, java.exam1, java.semend) demonstrating progressive mastery of OOP principles, data structures (linked lists, stacks, queues, trees), and algorithmic thinking through formal academic assessments.",
    impact: "Formally assessed Java proficiency — validated competency, not self-claimed",
    technologies: ["Java", "OOP", "Data Structures", "Algorithms"],
    github: "https://github.com/sarwansai8/java.exam",
    problem: [
      "Computer science students must demonstrate practical command of OOP principles — not just theoretical understanding — through working implementations across diverse problem domains.",
      "Academic examinations require solving complex programming problems under time constraints, demanding deep familiarity with Java syntax, standard libraries, and algorithmic problem-solving.",
      "Building strong Java fundamentals is essential before progressing to enterprise frameworks (Spring Boot, Hibernate) and distributed systems.",
      "Employers evaluating Java candidates need evidence of formal, assessed programming competency — not just self-taught projects — to validate true proficiency.",
    ],
    outcome: [
      "Successfully completed and submitted multiple assessed Java projects demonstrating command of OOP, data structures, and algorithmic implementation.",
      "Built working implementations of core data structures (arrays, linked lists, stacks, queues, trees) and sorting/searching algorithms through practical coding assessments.",
      "Established the Java fundamentals required to progress to Spring Boot, Android development, and enterprise backend engineering.",
      "Three separate project submissions (exam, exam1, semend) reflect consistent academic engagement and measurable skill progression.",
      "Validated Java proficiency through formal academic assessment — providing credibility beyond self-directed learning claims.",
    ],
    keyContributions: [
      "Formal academic assessment of Java OOP, data structures, and algorithm implementation.",
      "Covers encapsulation, inheritance, polymorphism, and abstraction across multiple projects.",
      "Three assessed submissions reflecting progression across a structured computer science curriculum.",
      "Foundation for Spring Boot, Android, and enterprise backend development.",
      "Validated proficiency — formally assessed, not self-claimed.",
    ],
  },
  {
    id: "11",
    title: "Deeptap — Android Data Collection APK",
    subtitle: "Stealth Android Security Research Tool",
    duration: "2024",
    category: "Mobile Security",
    status: "Completed",
    image: "/placeholder.svg",
    role: "Mobile Security Developer — Designed and implemented the Android application architecture and data collection logic.",
    description:
      "An Android application built for security research and controlled data collection, exploring the intersection of mobile application development and cybersecurity analysis. Compiled from Python to a fully functional Android APK using Kivy and Buildozer.",
    impact: "Python-to-APK compilation — rare capability beyond standard Android development pathways",
    technologies: ["Python", "Kivy", "Buildozer", "Android SDK"],
    github: "https://github.com/sarwansai8/deeptap_stealth_android_data_collection_apk",
    problem: [
      "Mobile security researchers and enterprise MDM teams lack open, transparent reference implementations for understanding how data collection occurs at the Android application layer.",
      "Understanding how malicious applications harvest device data is essential for building effective mobile threat defense systems — but this requires hands-on implementation experience.",
      "Android security auditors need practical knowledge of app permissions, background service behavior, and data exfiltration patterns to effectively assess and defend enterprise mobile fleets.",
      "Most mobile security tooling is desktop-centric — there is a significant gap for Python-based Android security research tools that can be compiled and deployed as native APKs.",
    ],
    outcome: [
      "Developed and compiled a fully functional Android APK using Python and Kivy/Buildozer — demonstrating end-to-end mobile application development.",
      "Implemented controlled data collection functionality providing practical insight into Android permissions model, background services, and application-layer data access.",
      "Gained hands-on understanding of Android security boundaries — directly applicable to mobile threat analysis, MDM policy design, and application security auditing.",
      "Demonstrated Python-to-Android compilation expertise via Buildozer — a rare technical capability beyond standard Java/Kotlin Android development pathways.",
      "Produced a research artifact that deepens understanding of how mobile data collection attacks work, enabling more effective defensive countermeasures.",
    ],
    keyContributions: [
      "Fully compiled Android APK developed entirely in Python using Kivy and Buildozer.",
      "Practical implementation of Android permissions model and background data collection.",
      "Research-grade tool providing insight into mobile threat patterns for defensive applications.",
      "Python-to-APK compilation — rare capability beyond standard Android development workflows.",
      "Applicable to MDM policy design, mobile forensics, and application security auditing.",
    ],
  },
]

export const skillsData = [
  {
    id: "1",
    name: "Network Security",
    category: "Cybersecurity",
    level: 90,
    description: "Deep understanding of network protocols, firewalls, IDS/IPS, and traffic analysis.",
    tools: ["Wireshark", "Nmap", "Snort", "Cisco Packet Tracer", "pfSense"],
    icon: Shield,
  },
  {
    id: "2",
    name: "Web Development",
    category: "Development",
    level: 85,
    description: "Full-stack development with security best practices baked in from the ground up.",
    tools: ["React", "Next.js", "Node.js", "TailwindCSS", "PostgreSQL"],
    icon: Globe,
  },
  {
    id: "3",
    name: "Ethical Hacking",
    category: "Cybersecurity",
    level: 82,
    description: "Identifying and exploiting vulnerabilities responsibly to harden system security.",
    tools: ["Metasploit", "Burp Suite", "Kali Linux", "OWASP ZAP"],
    icon: Terminal,
  },
  {
    id: "4",
    name: "Cloud Security",
    category: "Cybersecurity",
    level: 78,
    description: "Securing cloud workloads and infrastructure across AWS and Azure environments.",
    tools: ["AWS IAM", "AWS CloudTrail", "Azure Defender", "Terraform"],
    icon: Cloud,
  },
  {
    id: "5",
    name: "Application Security",
    category: "Development",
    level: 80,
    description: "SAST/DAST, secure SDLC, and dependency auditing to eliminate vulnerabilities at the code level.",
    tools: ["OWASP Top 10", "SonarQube", "Semgrep", "npm audit"],
    icon: Lock,
  },
  {
    id: "6",
    name: "DevSecOps & Containers",
    category: "Tools & Technologies",
    level: 75,
    description: "Container security, CI/CD pipeline hardening, and infrastructure-as-code best practices.",
    tools: ["Docker", "Kubernetes", "GitHub Actions", "Trivy"],
    icon: Box,
  },
]

export const postsData = [
  {
    id: "1",
    title: "Understanding Zero Trust Architecture",
    excerpt: "Why the traditional perimeter security model is failing and how Zero Trust provides a better alternative.",
    date: "2024-03-15",
    readTime: "5 min read",
    category: "Security",
    image: "/blog/zero-trust.jpg",
    slug: "zero-trust-architecture",
  },
  {
    id: "2",
    title: "The Future of AI in Cybersecurity",
    excerpt: "Exploring how Artificial Intelligence is both a tool for defense and a weapon for attackers.",
    date: "2024-03-10",
    readTime: "4 min read",
    category: "AI",
    image: "/blog/ai-security.jpg",
    slug: "ai-in-cybersecurity",
  },
  {
    id: "3",
    title: "Securing Next.js Applications",
    excerpt: "Best practices for building secure web applications with Next.js and React.",
    date: "2024-03-05",
    readTime: "6 min read",
    category: "Development",
    image: "/blog/nextjs-security.jpg",
    slug: "securing-nextjs",
  },
]

export const educationData = [
  {
    id: "1",
    degree: "Bachelor of Technology in Cybersecurity",
    institution: "Koneru Lakshmaiah Education Foundation (KL University)",
    location: "Guntur, Telangana",
    duration: "2021 – 2025",
    description:
      "Specializing in Network Security, Ethical Hacking, and Cloud Computing. Active member of the Cybersecurity Club and IEEE Student Branch. Completed capstone project on IoT security monitoring.",
    grade: "CGPA: 8.4 / 10",
  },
  {
    id: "2",
    degree: "Intermediate (MPC — 12th Grade)",
    institution: "Sri Chaitanya Junior College",
    location: "Hyderabad, Telangana",
    duration: "2019 – 2021",
    description:
      "Studied Mathematics, Physics, and Chemistry with distinction. Ranked in the top 5% of the batch and developed a strong analytical problem-solving foundation.",
    grade: "96.4%",
  },
  {
    id: "3",
    degree: "SSC (10th Grade)",
    institution: "Narayana High School",
    location: "Nalgonda, Telangana",
    duration: "2018 – 2019",
    description:
      "Graduated with outstanding academic performance. School topper in Mathematics. Participated in national-level science olympiads and academic quiz competitions.",
    grade: "GPA: 10 / 10",
  },
]

export const achievementsData = [
  {
    id: "1",
    title: "Certified Ethical Hacker (CEH)",
    category: "Certification",
    issuer: "EC-Council",
    date: "2024",
    description: "Demonstrated expertise in ethical hacking methodologies, penetration testing, and vulnerability assessment. Validated skills in network security, cryptography, and system hacking.",
    icon: "🏅",
    link: "",
    accent: "#9d5cff",
  },
  {
    id: "2",
    title: "CTF Competition — Top 10 Finalist",
    category: "Competition",
    issuer: "National Cyber League",
    date: "2024",
    description: "Secured top 10 position among 500+ participants in a national-level Capture The Flag competition. Solved challenges in web exploitation, cryptography, reverse engineering, and forensics.",
    icon: "🏆",
    link: "",
    accent: "#22d3ee",
  },
  {
    id: "3",
    title: "Google Cybersecurity Certificate",
    category: "Certification",
    issuer: "Google",
    date: "2024",
    description: "Completed comprehensive training in security operations, threat detection, incident response, and SIEM tools. Learned Python for security automation and Linux administration.",
    icon: "📜",
    link: "",
    accent: "#34d399",
  },
  {
    id: "4",
    title: "Best Security Project Award",
    category: "Award",
    issuer: "KL University",
    date: "2024",
    description: "Awarded for the CyberTrapX honeypot project in the annual university project exhibition. Recognized for innovation in threat detection and automated deployment systems.",
    icon: "🥇",
    link: "",
    accent: "#fbbf24",
  },
  {
    id: "5",
    title: "IEEE Student Member",
    category: "Membership",
    issuer: "IEEE",
    date: "2022 – Present",
    description: "Active member of IEEE Computer Society and Cybersecurity community. Participated in technical workshops, hackathons, and networking events with industry professionals.",
    icon: "🎖️",
    link: "",
    accent: "#818cf8",
  },
  {
    id: "6",
    title: "Open Source Contributor",
    category: "Recognition",
    issuer: "GitHub",
    date: "2023 – Present",
    description: "Actively contributing to open-source security tools and educational resources. Multiple repositories with 50+ stars combined, helping the cybersecurity community.",
    icon: "⭐",
    link: "https://github.com/sarwansai8",
    accent: "#f472b6",
  },
]
